import Head from "next/head";
import Image from "next/image";

// Components

import Banner from "@/components/banner/banner.component";
import Card from "@/components/card/card.component";

import styles from "@/styles/Home.module.css";

export default function Home() {
    const handleOnBannerBtnClick = () => {
        console.log("Banner button had been clicked");
    };

    return (
        <>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText="View stores nearby"
                    handleOnClick={handleOnBannerBtnClick}
                />
                <Image
                    className={styles.heroImage}
                    src="/static/img/hero-image.png"
                    alt="Sitting drinking cofee"
                    width={700}
                    height={400}
                />
                <Card
                    name="Coffee Store1"
                    imgUrl="/static/img/hero-image.png"
                    href="/coffee-store/coffe-store1"
                />
            </main>
        </>
    );
}
